### ISSUE TITLE
Introduction.

### ISSUE THREAD

**Issue by Joyce-Stack** [slyg/graphql-mendeley#1]
Apologies for creating an issue for this I was looking to get in touch with you. I'm Joyce and I'm the Developer Advocate on the Mendeley API. 

I'm thinking of writing a blog post on this on our engineering blog (full credit to you obviously) and perhaps putting it on our developer portal as a helper library if you are agreeable. 

If you feel more comfortable discussing via email then my contact details are joyce.stack@mendeley.com.

**Comment by slyg** [comment]
@MendeleyStack I'm so sorry I haven't answered before, just saw it today actually :confused:. No problem linking to this repo. It's nice to you that you that you sent a message, I saw your post since then. Thx!
